# strip method in python

name = "    Harshit    "
dots = " ............. "
# strip() method
print(name.lstrip() + dots) #output- Harshit    ..............
print(name.rstrip() + dots) #output-     Harshit..............
print(name.strip() + dots) #output- Harshit.............
